#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "GCP + BigQuery setup (free tier, oauth ADC)"

# ── Stage 1: create the GCP project ────────────────────────────────────────
stage "Create GCP project"
say "This project will hold the BigQuery raw dataset for the loader script."
open_url "https://console.cloud.google.com/projectcreate"
step "Give it any name (e.g. 'ecommerce-elt-pipeline')."
step "Copy the Project ID shown under the name field (not the display name —"
step "it's the lowercase-with-dashes id, may differ from what you typed)."
ask GOOGLE_CLOUD_PROJECT "Paste the Project ID:"
write_env GOOGLE_CLOUD_PROJECT "$GOOGLE_CLOUD_PROJECT"
note "BigQuery works without a billing account in 'sandbox mode' (free, but"
note "datasets expire after 60 days and streaming inserts are disabled)."
note "For an unrestricted free-tier setup, you can attach a billing account"
note "with Google's free trial credit instead — your call, both cost \$0 here."
if confirm "Attach a billing account now (recommended, skip to stay sandbox-only)?"; then
  open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GOOGLE_CLOUD_PROJECT"
  step "Link an existing billing account, or start the free trial, then link it."
  pause "Press Enter once billing is linked (or skipped on purpose)."
fi

# ── Stage 2: enable the BigQuery API ───────────────────────────────────────
stage "Enable BigQuery API"
open_url "https://console.cloud.google.com/apis/library/bigquery.googleapis.com?project=$GOOGLE_CLOUD_PROJECT"
step "Click 'Enable' (it may already be enabled on a new project — that's fine)."
pause "Press Enter once it shows as enabled."

# ── Stage 3: install the gcloud CLI ────────────────────────────────────────
stage "Install gcloud CLI"
if command -v gcloud >/dev/null 2>&1; then
  note "gcloud already installed ($(gcloud --version | head -n1)) — skipping."
else
  say "dbt authenticates to BigQuery locally via gcloud's Application Default"
  say "Credentials, so the CLI needs to be on your PATH."
  open_url "https://cloud.google.com/sdk/docs/install-sdk#windows"
  step "Download the Google Cloud CLI installer for Windows and run it."
  step "Accept the defaults; let it open a new terminal / add itself to PATH."
  step "Open a NEW terminal window after install finishes (PATH won't update"
  step "in this one)."
  pause "Press Enter once 'gcloud --version' works in a fresh terminal."
fi

# ── Stage 4: gcloud login + set project ────────────────────────────────────
stage "gcloud login"
say "This opens a browser to sign in with the Google account that owns the"
say "project above."
note "Run these in your OWN terminal (not this wizard), since they open a"
note "browser and need your live session:"
step "gcloud auth login"
step "gcloud config set project $GOOGLE_CLOUD_PROJECT"
pause "Press Enter once both commands finished."

# ── Stage 5: Application Default Credentials for dbt ──────────────────────
stage "Application Default Credentials (dbt oauth)"
say "dbt-bigquery's 'oauth' auth method reads these ADC credentials — this is"
say "the step that actually lets dbt query BigQuery."
note "Run in your own terminal:"
step "gcloud auth application-default login"
note "This also sets a quota project. If dbt later complains about a missing"
note "quota project, run:"
step "gcloud auth application-default set-quota-project $GOOGLE_CLOUD_PROJECT"
pause "Press Enter once application-default login finished."

write_env GCP_AUTH_METHOD "oauth"

finish

note "Next: hand this back to the agent to scaffold the dbt project, Python"
note "loader env, and create the 'raw' BigQuery dataset via bq/dbt using"
note "GOOGLE_CLOUD_PROJECT from .env."
